import { Roboto } from "next/font/google";
import "./globals.css";
import { Directions, Languages } from "../../constants/constants";

import ProductProvider from "../../context/ProductContext";
import { ClerkProvider } from "@clerk/nextjs";
import HeaderWraper from "../../components/header/HeaderWraper";
import CartProvider from "../../context/CartContext";
import Cart from "./_component/cart/Cart";
import CartButtonProvider from "../../context/CartButtonContext";
import OrderProvider from "../../context/OrderContext";
import Footer from "../../components/footer/Footer";
import Provider from "../../components/provider/Provider";
import UserProvider from "../../context/UserContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "SkillCode – Learn, Code, Launch",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const locale = await params.locale;
  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body className={` ${roboto.className} antialiased`}>
        <ClerkProvider>
          <ProductProvider>
            <CartProvider>
              <OrderProvider>
                <UserProvider>
                  <CartButtonProvider>
                    <HeaderWraper locale={locale} />
                    <Cart />
                  </CartButtonProvider>
                  <Provider>{children}</Provider>
                  <Footer />
                </UserProvider>
              </OrderProvider>
            </CartProvider>
          </ProductProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
